services:
  api:
    build:
      context: .
    ports:
      - "8003:8000"
    restart: unless-stopped
    container_name: news-api
    environment:
      NEWS_SEARXNG_URL: http://searxng:8080
      NEWS_OLLAMA_URL: http://host.docker.internal:11434
      NEWS_OLLAMA_CHAT_MODEL: qwen3.5:9b
      NEWS_OLLAMA_EMBEDDING_MODEL: mxbai-embed-large
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet

networks:
  appnet:
    external: true

